spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cdr_prod
        username: cdr_prod_user
        password: password
    sql:
        init:
            platform: mysql
    jpa:
        hibernate:
            ddl-auto: validate
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5MariaDBDialect

