spring:
    datasource:
        url: jdbc:h2:mem:test
#            driverClassName: org.h2.Driver
        username: sa
    h2:
        console:
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    sql:
        init:
            data-locations: classpath:/database-init/data/*.sql
#            schema-locations: