spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:h2:mem:test
        username: cdr_dev_user
        password: password
    sql:
        init:
            platform: mysql
    jpa:
        hibernate:
            ddl-auto: validate
            use-new-id-generator-mappings: false
        database-platform: org.hibernate.dialect.MySQL8Dialect
        database: mysql

